services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    volumes:
      - mongodb_data:/data/db  # Том для хранения данных
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Порт для взаимодействия приложений
      - "15672:15672"  # Порт для доступа к веб-интерфейсу управления
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"  # Порт для веб-интерфейса Mongo-Express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: user
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Порт Redis
    restart: always
    volumes:
      - redis_data:/data  # Том для хранения данных

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200" # Порт для веб-интерфейса OpenSearch
      - "9600:9600" # Для мониторинга OpenSearch
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    depends_on:
      - opensearch
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044" # Для отправки логов
    restart: always

  kibana:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: kibana
    depends_on:
      - opensearch
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
    ports:
      - "5601:5601" # Порт для веб-интерфейса Kibana
    restart: always

volumes:
  mongodb_data:  # Том для хранения данных
  redis_data:
  opensearch_data:
