#gRPC client properties
grpc:
  client:
    local-grpc-server:
      address: "static://localhost:9090"
      enable-keep-alive: true

#RabbitMQ properties
spring:
  rabbitmq:
    host: localhost
    virtual-host: /
    password: guest
    username: guest
    port: 5672

#Redis properties
  redis:
    host: localhost
    port: 6379

