#gRPC client properties
grpc:
  client:
    local-grpc-server:
      address: "static://domain:9090"
      enable-keep-alive: true

#RabbitMQ properties
spring:
  rabbitmq:
    host: rabbitmq
    virtual-host: /
    password: guest
    username: guest
    port: 5672

#Redis properties
  redis:
    host: redis
    port: 6379

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

